### ISSUE TITLE
The Land Use Summary shows NA for urban areas

### ISSUE THREAD

**Issue by celray** [swat-model/swatplus-editor#4]
If urban land (of any type) is available in the model setup, the checker section shows it as NA instead of the actual name.

**To Reproduce**
Set up a model with any urban land use code (e.g. urld, urmd) in land use lookup in QSWAT+
1. Import into SWAT+ Editor
2. Run for any period and import Results
3. Go to SWAT Checker Section
4. Navigate to Land Use Summary
5. The urban area (recognisable by covered area) will be labelled NA in the LULC column

**Expected behavior**
This should be labelled the land use code retrieved from the urban table of the project database

**Screenshots**
![urbanIssue](https://github.com/user-attachments/assets/2c2be530-7d40-4c19-90ae-1f414c694a35)

**Desktop**
- OS: This applies on all platforms

**Comment by jaclynt** [comment]
Thanks, will fix soon. I see I have a bug looking up the land use codes for HRUs. Originally to keep it simple and attempting to just read from outputs only, we were matching HRU land uses from crop_yld_aa. Later when I realized this didn't have urban land uses included, I had to find those a different way, but did so incorrectly. I will switch it to finding the land use correctly from the inputs instead.

**Comment by jaclynt** [comment]
This is now fixed in the [v3.0.4 release](https://github.com/swat-model/swatplus-editor/releases/tag/v3.0.4)

Commit [ba9541b](https://github.com/swat-model/swatplus-editor/commit/ba9541bcce9cba3fbeae075603b443ab0bac4848)
Commit [b1936b8](https://github.com/swat-model/swatplus-editor/commit/b1936b8c63f38f77ca8abeeefb183a1c0f66f999)

**Comment by jaclynt** [comment]
This is now fixed in the [v3.0.4 release](https://github.com/swat-model/swatplus-editor/releases/tag/v3.0.4)

Commit [ba9541b](https://github.com/swat-model/swatplus-editor/commit/ba9541bcce9cba3fbeae075603b443ab0bac4848)
Commit [b1936b8](https://github.com/swat-model/swatplus-editor/commit/b1936b8c63f38f77ca8abeeefb183a1c0f66f999)
